const imageByName = {
  'NAA 4.5% SL': '/products/auth/naa.jpg',
  'Abamectin 1.9% EC': '/products/auth/abamectin.webp',
  'Acephate 75% SP': '/products/auth/acephate.webp',
  'Acetamiprid 20% SP': '/products/auth/acetamiprid.webp',
  'Aluminum Phosphide 56%': '/products/auth/aluminium-phosphide.jpg',
  'Brodifacoum 0.005% BB': '/products/auth/brodifacoum.jpg',
  'Chlorantraniliprole 18.5% SC': '/products/auth/imidacloprid.jpg',
  'Cypermethrin 10% EC': '/products/auth/cypermethrin.webp',
  'Deltamethrin 2.8% EC': '/products/auth/deltamethrin.webp',
  'Imidacloprid 70% WG': '/products/auth/imidacloprid.jpg',
  'Thiamethoxam 25% WG': '/products/auth/thiamethoxam.jpg',
  'Acephate 50% + Imidacloprid 1.8% SP': '/products/auth/acephate.webp',
  'Chlorantraniliprole 9.3% + Lambda-cyhalothrin 4.6% ZC': '/products/auth/abamectin.webp',
  'Lambda-cyhalothrin 9.7% CS': '/products/auth/imidacloprid.jpg',
  'Rupiya Kuber': '/products/auth/rupiya_kuber.png',
  'Urea 45kg': '/products/auth/urea.jpg',
  'Vermicompost 50kg': '/products/auth/vermicompost.jpg',
  'NPK 19:19:19 1kg': '/products/auth/npk19.jpg',
  'Trichoderma Viride 1kg': '/products/auth/trichoderma.jpg',
  'Tomato Seeds (Hybrid) 10g': '/products/auth/tomato_seeds.png'
};

const d = (a, b) => `${a}. ${b}.`;

const categoryTag = {
  Fertilizer: 'Crop Nutrition',
  Pesticide: 'Crop Protection',
  Seed: 'Certified Seed',
  'Soil Amendment': 'Soil Health',
  'Farm Tools': 'Farm Utility'
};

const make = (id, c) => ({
  id,
  name: c.n,
  category: c.c,
  tag: c.tag || categoryTag[c.c],
  color: c.clr,
  description: c.d1,
  longDescription: c.longDesc || `${c.d1} ${c.d2}`,
  features: c.feat || [c.d1, c.d2],
  price: c.p,
  rating: c.r || 4.5,
  reviewCount: c.rc || Math.floor(Math.random() * 100) + 50,
  image: imageByName[c.n] || '/products/auth/naa.jpg',
  imageUrl: c.img,
  sellerName: 'FasalRakshak Direct',
  sellerLocation: 'Pune, Maharashtra',
  sellerPhone: '919979265140',
  isRecommended: c.rec || false,
  inStock: c.stock !== false,
  badge: c.b,
  specs: {
    weight: c.w || 'Standard',
    composition: c.comp || c.n,
    dosage: c.dose || 'As per recommendation',
    applicationMethod: c.app || 'Foliar spray',
    suitableFor: c.crops || []
  },
  usage: c.usage || {},
  whyUse: [c.w1, c.w2].filter(Boolean).join(' '),
  recommendedCrops: c.crops || [],
  season: c.season || 'Both',
  translationKey: c.tk
});

const rows = [
  [1, {
    n: 'NAA 4.5% SL',
    c: 'Pesticide',
    tag: 'Plant Growth Regulator',
    p: 340,
    r: 4.7,
    rc: 128,
    rec: true,
    stock: true,
    b: 'Bestseller',
    clr: '#4A6B8F',
    img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSEOzbC1ewJt0FDo4D6eFugAE9TOwtid_uve639m_hygRt6jr9Hv8HOdoERE4X38JD7lDkiq7oj_USjze5IH-K7qgFtT7OWVSe6ijPO8mNjiLG8qlYnh7cue30pqM2h3uY4kp-SRA&usqp=CAc',
    w: '250ml',
    comp: 'Naphthalene Acetic Acid 4.5% SL',
    dose: '20-444 ml per acre',
    app: 'Foliar spray',
    crops: ['Cotton', 'Tomato', 'Mango'],
    season: 'Both',
    d1: 'Prevents flower and fruit drop in a wide range of crops.',
    d2: 'Improves fruit set and retention, enhancing overall crop yield.',
    w1: 'Use it to prevent premature shedding of flowers and fruits.',
    longDesc: 'NAA (Naphthalene Acetic Acid) 4.5% SL is a synthetic plant hormone in the auxin family. It is primarily used to prevent the premature shedding of flowers, squares, and bolls, thereby improving fruit set and overall yield.',
    feat: ['Prevents flower and fruit drop', 'Improves fruit set and retention', 'Enhances overall crop yield', 'Promotes root growth in cuttings', 'Suitable for foliar application'],
    usage: { tomato: '20-40 ml in 1000 L water per ha', cotton: '222-444 ml in 1000 L water per ha', mango: '15 ml formulation per 100 L water' },
    tk: 'NAA'
  }],
  [2, {
    n: 'Abamectin 1.9% EC',
    c: 'Pesticide',
    tag: 'Miticide / Insecticide',
    p: 216,
    r: 4.5,
    rc: 89,
    rec: true,
    stock: true,
    clr: '#2E7D32',
    img: 'https://agribegri.com/_next/image?url=https%3A%2F%2Fdujjhct8zer0r.cloudfront.net%2Fmedia%2Fprod_image%2F9076641391771574284.webp&w=750&q=90',
    w: '100ml',
    comp: 'Abamectin 1.9% EC',
    dose: '0.025-0.75 ml/L',
    app: 'Foliar spray',
    crops: ['Rose', 'Grapes', 'Apple', 'Tomato'],
    season: 'Both',
    d1: 'Effective against mites and leaf miners in a variety of crops.',
    d2: 'Acts through contact and stomach action with long-lasting protection.',
    w1: 'Use it for controlling spider mites and leaf miners.',
    longDesc: 'Abamectin 1.9% EC is a mixture of avermectins, producing toxic effects in insects and mites by stimulating the release of gamma-aminobutyric acid (GABA).',
    feat: ['Effective against red spider mites and leaf miners', 'Acts through contact and stomach action', 'Recommended for roses, grapes, apples, tomatoes', 'Provides long-lasting protection', 'Rapidly degrades on plant surfaces'],
    usage: { rose: '0.025-0.05% solution in 5000 L water per ha', grapes: '0.75 ml/L water in 500-1000 L water per ha', apple: '0.05% solution, 6-7 L water per tree', tomato: '450-600 ml in 500 L water per ha' },
    tk: 'Abamectin'
  }],
  [3, {
    n: 'Acephate 75% SP',
    c: 'Pesticide',
    tag: 'Systemic Insecticide',
    p: 450,
    r: 4.3,
    rc: 156,
    rec: false,
    stock: true,
    clr: '#1b4a2b',
    img: 'https://agribegri.com/_next/image?url=https%3A%2F%2Fdujjhct8zer0r.cloudfront.net%2Fmedia%2Fprod_image%2F8651509761758697120.webp&w=640&q=90',
    w: '500g',
    comp: 'Acephate 75% SP',
    dose: '292-780 g per acre',
    app: 'Foliar spray',
    crops: ['Cotton', 'Rice', 'Safflower'],
    season: 'Both',
    d1: 'Broad-spectrum systemic insecticide for sucking and chewing pests.',
    d2: 'Water-soluble for easy application with systemic action.',
    w1: 'Use it for controlling jassids, bollworms, aphids, and stem borers.',
    longDesc: 'Acephate 75% SP is a soluble powder that acts as a systemic and contact insecticide. It is absorbed by leaves and roots, providing effective control against a wide range of pests.',
    feat: ['Systemic action for long-lasting control', 'Effective against both sucking and chewing insects', 'Water-soluble for easy application', 'Suitable for cotton, paddy, and safflower', 'Reduces pest populations quickly'],
    usage: { cotton_jassids: '292 g a.i./ha (390 g formulation)', cotton_bollworms: '584 g a.i./ha (780 g formulation)', rice_pests: '500-750 g a.i./ha' },
    tk: 'Acephate'
  }],
  [4, {
    n: 'Acetamiprid 20% SP',
    c: 'Pesticide',
    tag: 'Neonicotinoid',
    p: 340,
    r: 4.6,
    rc: 203,
    rec: true,
    stock: true,
    b: 'Popular',
    clr: '#556B2F',
    img: 'https://agribegri.com/_next/image?url=https%3A%2F%2Fdujjhct8zer0r.cloudfront.net%2Fmedia%2Fprod_image%2F7512801971733205868.webp&w=750&q=90',
    w: '100g',
    comp: 'Acetamiprid 20% SP',
    dose: '10-20 g a.i./ha',
    app: 'Foliar spray',
    crops: ['Cotton', 'Cabbage', 'Okra', 'Chilli', 'Rice'],
    season: 'Both',
    d1: 'Systemic insecticide for effective control of sap-feeding insects.',
    d2: 'Quick knockdown effect with broad-spectrum activity.',
    w1: 'Use it for controlling aphids, jassids, thrips, and whiteflies.',
    longDesc: 'Acetamiprid 20% SP is a systemic, neonicotinoid insecticide that acts on the central nervous system of insects, causing paralysis and death.',
    feat: ['Powerful systemic and translaminar activity', 'Controls broad spectrum of sucking pests', 'Quick knockdown effect', 'Safe to beneficial insects', 'Compatible with IPM programs'],
    usage: { cotton_aphids_jassids: '10 g a.i./ha (50 g formulation)', cotton_whiteflies: '20 g a.i./ha (100 g formulation)', cabbage_aphids: '15 g a.i./ha (75 g formulation)', okra_aphids: '15 g a.i./ha (75 g formulation)' },
    tk: 'Acetamiprid'
  }],
  [5, {
    n: 'Aluminum Phosphide 56%',
    c: 'Pesticide',
    tag: 'Fumigant',
    p: 216,
    r: 4.2,
    rc: 67,
    rec: false,
    stock: true,
    clr: '#8B4513',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAEWy7Yte9W0_GRp14iAufNxralI7sYg7Yjg&s',
    w: '500g',
    comp: 'Aluminum Phosphide 56%',
    dose: '3 tablets per ton',
    app: 'Fumigation',
    crops: ['Cereals', 'Pulses', 'Oilseeds', 'Spices'],
    season: 'Both',
    d1: 'Highly effective fumigant for stored grain pest control.',
    d2: 'Penetrates deep into grain stacks, killing all insect stages.',
    w1: 'Use it for controlling weevils, borers, and beetles in storage.',
    longDesc: 'Aluminum Phosphide 56% is a solid fumigant that reacts with moisture in the air to release phosphine gas.',
    feat: ['Highly effective against all stages of stored grain pests', 'Penetrates deep into grain stacks', 'Available in tablet and pouch formulations', 'Kills insects without leaving residues', 'Also used for rodent burrow fumigation'],
    usage: { cereals_pulses: '3 tablets (3g) per ton or 150g/100m³', oilseeds_spices: '3 tablets per ton or 225g/100m³', godowns: '14 tablets/1000m³ or 150g/100m³' },
    tk: 'AluminumPhosphide'
  }],
  [6, {
    n: 'Brodifacoum 0.005% BB',
    c: 'Pesticide',
    tag: 'Rodenticide',
    p: 450,
    r: 4.4,
    rc: 92,
    rec: false,
    stock: true,
    clr: '#4A2C2C',
    img: 'https://www.pestfix.co.uk/images/product-images/BB063%20RodentFix%20BF%20Brodifacoum%2050%20Bait%20Blocks%20800.jpg',
    w: '1kg',
    comp: 'Brodifacoum 0.005% BB',
    dose: 'One bait block per baiting station',
    app: 'Baiting',
    crops: ['Field', 'Residential', 'Godowns'],
    season: 'Both',
    d1: 'Potent, single-feed anticoagulant rodenticide for field and premises.',
    d2: 'Effective as a single-dose bait against wide variety of rodents.',
    w1: 'Use it for controlling rats, bandicoots, and mice.',
    longDesc: 'Brodifacoum 0.005% BB is a powerful anticoagulant rodenticide. It works by inhibiting the synthesis of Vitamin K, essential for blood clotting.',
    feat: ['Effective as a single-dose bait', 'Controls wide variety of rodent species', 'Ready-to-use block formulation', 'Ideal for use in and around buildings', 'Palatable bait matrix'],
    usage: { field_rats: 'One bait block (20g) per baiting station as single feed', residential: 'Place in and around premises, godowns, warehouses', burrow_baiting: 'Place bait near active burrows' },
    tk: 'Brodifacoum'
  }],
  [7, {
    n: 'Chlorantraniliprole 18.5% SC',
    c: 'Pesticide',
    tag: 'Anthranilic Diamide',
    p: 340,
    r: 4.8,
    rc: 145,
    rec: true,
    stock: true,
    b: 'Premium',
    clr: '#2E4E5F',
    img: 'https://agribegri.com/_next/image?url=https%3A%2F%2Fdujjhct8zer0r.cloudfront.net%2Fmedia%2Fprod_image%2F7512801971733205868.webp&w=750&q=90',
    w: '250ml',
    comp: 'Chlorantraniliprole 18.5% SC',
    dose: '30-40 g a.i./ha',
    app: 'Foliar spray',
    crops: ['Rice', 'Cotton', 'Cabbage', 'Tomato', 'Chilli', 'Brinjal'],
    season: 'Both',
    d1: 'Targets lepidopteran pests by disrupting their muscle contraction.',
    d2: 'Long-lasting residual control, safe to mammals and beneficial insects.',
    w1: 'Use it for controlling stem borers, fruit borers, and caterpillars.',
    longDesc: 'Chlorantraniliprole 18.5% SC belongs to the anthranilic diamide class of insecticides. It works by activating the ryanodine receptors in insects.',
    feat: ['Excellent control of lepidopteran pests', 'Acts on insect muscle systems', 'Long-lasting residual control', 'Safe to mammals and beneficial insects', 'Larvicidal and ovicidal properties'],
    usage: { rice: '30 g a.i./ha (150 ml) in 500 L water', cabbage: '10 g a.i./ha (50 ml) in 500 L water', cotton: '30 g a.i./ha (150 ml) in 500 L water', tomato: '30 g a.i./ha (150 ml) in 500 L water' },
    tk: 'Chlorantraniliprole'
  }],
  [8, {
    n: 'Cypermethrin 10% EC',
    c: 'Pesticide',
    tag: 'Pyrethroid',
    p: 216,
    r: 4.4,
    rc: 178,
    rec: false,
    stock: true,
    clr: '#D2691E',
    img: 'https://static-cdn.pestobazaar.com/product-image/suqX5PYae4oH8azcPeHX.webp',
    w: '500ml',
    comp: 'Cypermethrin 10% EC',
    dose: '50-70 g a.i./ha',
    app: 'Foliar spray',
    crops: ['Cotton', 'Cabbage', 'Okra', 'Brinjal', 'Wheat'],
    season: 'Both',
    d1: 'Fast-acting, broad-spectrum insecticide for diverse crops.',
    d2: 'Rapid knockdown and strong repellent action.',
    w1: 'Use it for controlling bollworms, diamondback moths, and jassids.',
    longDesc: 'Cypermethrin 10% EC is a synthetic pyrethroid insecticide that acts on the nervous system of insects, providing quick knockdown and kill.',
    feat: ['Rapid knockdown and strong repellent action', 'Broad-spectrum activity', 'Effective against wide range of field pests', 'Stable in sunlight for good residual activity', 'Suitable for IPM integration'],
    usage: { cotton: '50-70 g a.i./ha (550-760 ml)', cabbage: '60-70 g a.i./ha (650-760 ml)', okra: '50-70 g a.i./ha (550-760 ml)', brinjal: '50-70 g a.i./ha (550-760 ml)' },
    tk: 'Cypermethrin'
  }],
  [9, {
    n: 'Deltamethrin 2.8% EC',
    c: 'Pesticide',
    tag: 'Pyrethroid',
    p: 450,
    r: 4.6,
    rc: 167,
    rec: true,
    stock: true,
    b: 'High Potency',
    clr: '#B8860B',
    img: 'https://static-cdn.pestobazaar.com/product-image/5EQp2BJFZW05x575HDzJ.webp',
    w: '250ml',
    comp: 'Deltamethrin 2.8% EC',
    dose: '10-15 g a.i./ha',
    app: 'Foliar spray',
    crops: ['Cotton', 'Tea', 'Okra', 'Chilli', 'Groundnut'],
    season: 'Both',
    d1: 'High-potency insecticide for agriculture and public health.',
    d2: 'Effective at very low doses with rapid knockdown.',
    w1: 'Use it for controlling bollworms, leaf folders, thrips, and borers.',
    longDesc: 'Deltamethrin 2.8% EC is a highly potent synthetic pyrethroid insecticide. It disrupts the nervous system of insects, causing immediate paralysis.',
    feat: ['Extremely high insecticidal activity', 'Effective at very low doses', 'Used for crop protection and public health', 'Rapid knockdown and good residual effect', 'Effective against wide range of insect pests'],
    usage: { cotton: '12.5 g a.i./ha (500 ml)', tea_thrips: '3-4 g a.i./ha (120-150 ml)', okra: '10-15 g a.i./ha (400-600 ml)', public_health_mosquito: 'Thermal fogging 0.5 g a.i./ha' },
    tk: 'Deltamethrin'
  }],
  [10, {
    n: 'Imidacloprid 70% WG',
    c: 'Pesticide',
    tag: 'Neonicotinoid',
    p: 340,
    r: 4.7,
    rc: 234,
    rec: true,
    stock: true,
    b: 'Bestseller',
    clr: '#2E5A8B',
    img: 'https://cdn.shopify.com/s/files/1/0722/2059/files/admire-insecticide-file-20004.jpg?v=1747131488&width=640&format=webp',
    w: '100g',
    comp: 'Imidacloprid 70% WG',
    dose: '21-63 g a.i./ha',
    app: 'Foliar spray / Drip',
    crops: ['Cotton', 'Rice', 'Okra', 'Cucumber', 'Tomato', 'Potato'],
    season: 'Both',
    d1: 'Systemic insecticide for long-lasting control of sucking pests.',
    d2: 'Provides long-term protection up to several weeks.',
    w1: 'Use it for controlling jassids, aphids, thrips, and whiteflies.',
    longDesc: 'Imidacloprid 70% WG is a systemic insecticide from the neonicotinoid group. It is absorbed by plants and moves through the vascular system.',
    feat: ['Powerful systemic action', 'Provides long-term protection', 'Highly effective against sucking insects', 'Water-dispersible granule for easy mixing', 'Reduced risk to environment'],
    usage: { cotton: '21-24.5 g a.i./ha (30-35 g)', rice: '21-24.5 g a.i./ha (30-35 g)', okra: '21-24.5 g a.i./ha (30-35 g)', tomato: '35 g a.i./ha (50 g)' },
    tk: 'Imidacloprid'
  }],
  [11, {
    n: 'Thiamethoxam 25% WG',
    c: 'Pesticide',
    tag: 'Neonicotinoid',
    p: 216,
    r: 4.5,
    rc: 189,
    rec: false,
    stock: true,
    clr: '#3A6B4B',
    img: 'https://katyayanikrishidirect.com/cdn/shop/files/Thioxam75Emazar.jpg?v=1752907805&width=823',
    w: '100g',
    comp: 'Thiamethoxam 25% WG',
    dose: '12.5-50 g a.i./ha',
    app: 'Foliar spray / Seed treatment',
    crops: ['Rice', 'Cotton', 'Okra', 'Mango', 'Wheat'],
    season: 'Both',
    d1: 'Systemic insecticide with rapid action for comprehensive crop protection.',
    d2: 'Excellent systemic and translaminar movement.',
    w1: 'Use it for controlling broad spectrum of sucking and some chewing pests.',
    longDesc: 'Thiamethoxam 25% WG is a second-generation neonicotinoid insecticide with excellent systemic and translaminar activity.',
    feat: ['Broad-spectrum control of sucking pests', 'Excellent systemic and translaminar movement', 'Rapid uptake by plants', 'Long residual activity', 'Can be applied as spray, drench, or seed treatment'],
    usage: { rice: '25 g a.i./ha (100 g)', cotton_jassid: '25 g a.i./ha (100 g)', cotton_whitefly: '50 g a.i./ha (200 g)', okra: '25 g a.i./ha (100 g)' },
    tk: 'Thiamethoxam'
  }],
  [12, {
    n: 'Acephate 50% + Imidacloprid 1.8% SP',
    c: 'Pesticide',
    tag: 'Combination SP',
    p: 450,
    r: 4.6,
    rc: 112,
    rec: true,
    stock: true,
    b: 'Combo Deal',
    clr: '#4A5D3A',
    img: 'https://agribegri.com/_next/image?url=https%3A%2F%2Fdujjhct8zer0r.cloudfront.net%2Fmedia%2Fprod_image%2F7512801971733205868.webp&w=750&q=90',
    w: '1kg',
    comp: 'Acephate 50% + Imidacloprid 1.8% SP',
    dose: '518 g a.i./ha',
    app: 'Foliar spray',
    crops: ['Cotton', 'Rice', 'Sugarcane', 'Chilli'],
    season: 'Both',
    d1: 'Powerful combination for controlling both sucking and borer pests.',
    d2: 'Dual mode of action for resistance management.',
    w1: 'Use it for managing complex pest infestations.',
    longDesc: 'This combination product harnesses the systemic and contact action of Imidacloprid with the broad-spectrum activity of Acephate.',
    feat: ['Dual mode of action for resistance management', 'Controls wide spectrum of sucking pests and bollworms', 'Synergistic effect for enhanced pest control', 'Ideal for crops with multiple pest complexes', 'Water-soluble powder for easy application'],
    usage: { cotton: '518 g a.i./ha (1000 g)', rice: '518 g a.i./ha (1000 g)', sugarcane: '1250+45 g a.i./ha (2500 ml)', chilli: '518 g a.i./ha (1000 g)' },
    tk: 'AcephateImida'
  }],
  [13, {
    n: 'Chlorantraniliprole 9.3% + Lambda-cyhalothrin 4.6% ZC',
    c: 'Pesticide',
    tag: 'Combination ZC',
    p: 340,
    r: 4.7,
    rc: 98,
    rec: true,
    stock: true,
    b: 'New',
    clr: '#5A3D2E',
    img: 'https://agribegri.com/_next/image?url=https%3A%2F%2Fdujjhct8zer0r.cloudfront.net%2Fmedia%2Fprod_image%2F9076641391771574284.webp&w=750&q=90',
    w: '250ml',
    comp: 'Chlorantraniliprole 9.3% + Lambda-cyhalothrin 4.6% ZC',
    dose: '28-37.5 g a.i./ha',
    app: 'Foliar spray',
    crops: ['Pigeon Pea', 'Cotton', 'Brinjal', 'Okra', 'Rice', 'Soybean', 'Maize'],
    season: 'Both',
    d1: 'Potent mix of diamide and pyrethroid for rapid and residual control.',
    d2: 'Provides both quick knockdown and long-lasting residual control.',
    w1: 'Use it for controlling fruit borers, bollworms, leaf folders, and jassids.',
    longDesc: 'This combination formulation contains Chlorantraniliprole (a ryanodine receptor modulator) and Lambda-cyhalothrin (a sodium channel modulator).',
    feat: ['Two powerful modes of action', 'Quick knockdown (Lambda-cyhalothrin) and long residual (Chlorantraniliprole)', 'Broad-spectrum control', 'Effective resistance management tool', 'Protects yield and quality'],
    usage: { pigeon_pea: '30 g a.i./ha (200 ml)', cotton: '37.5 g a.i./ha (250 ml)', brinjal: '28 g a.i./ha (200 ml)', rice: '28-35 g a.i./ha (200-250 ml)' },
    tk: 'ChlLambda'
  }],
  [14, {
    n: 'Lambda-cyhalothrin 9.7% CS',
    c: 'Pesticide',
    tag: 'Public Health Insecticide',
    p: 216,
    r: 4.3,
    rc: 45,
    rec: false,
    stock: true,
    clr: '#2E5A8B',
    img: 'https://agribegri.com/_next/image?url=https%3A%2F%2Fdujjhct8zer0r.cloudfront.net%2Fmedia%2Fprod_image%2F7512801971733205868.webp&w=750&q=90',
    w: '500ml',
    comp: 'Lambda-cyhalothrin 9.7% CS',
    dose: '20-25 mg a.i./sq.m',
    app: 'Indoor Residual Spray',
    crops: ['Public Health', 'Malaria Control'],
    season: 'Both',
    d1: 'Microencapsulated formulation for effective mosquito control.',
    d2: 'Longer-lasting residual effect on various wall surfaces.',
    w1: 'Use it for Indoor Residual Spraying (IRS) to control mosquitoes.',
    longDesc: 'Lambda-cyhalothrin 9.7% CS is a public health insecticide formulated for indoor residual spraying (IRS).',
    feat: ['Microencapsulated for enhanced safety and residual life', 'Used for Indoor Residual Spraying (IRS)', 'Effective against Anopheles, Aedes, and Culex mosquitoes', 'Long-lasting efficacy on surfaces', 'Approved for public health programs'],
    usage: { malaria_control: '25 mg a.i./sq.m (12.5 ml/500 sq.m) in 10 L water', moderate_infestation: '20 mg a.i./sq.m (4 ml/L water)', high_infestation: '25 mg a.i./sq.m (5 ml/L water)' },
    tk: 'LambdaCS'
  }],
  [15, {
    n: 'Rupiya Kuber',
    c: 'Fertilizer',
    tag: 'Liquid Manure Supplement',
    p: 450,
    r: 4.8,
    rc: 76,
    rec: true,
    stock: true,
    b: 'Organic',
    clr: '#B8860B',
    img: '/products/auth/rupiya_kuber.png',
    w: '5L',
    comp: 'Natural Liquid Manure',
    dose: '5-10 ml per liter',
    app: 'Foliar spray / Drip',
    crops: ['All Crops', 'Vegetables', 'Fruits', 'Flowers'],
    season: 'Both',
    d1: 'Natural liquid manure supplement providing balanced potassium, carbon, and magnesium.',
    d2: 'Increases productivity and quality of crops.',
    w1: 'Use it to enhance photosynthesis and pollen germination.',
    longDesc: "It's a natural liquid manure supplement which provides balanced amounts of potassium, carbon and magnesium to the crop.",
    feat: ['Increases productivity and quality of crops', 'Enhances photosynthesis and pollen germination', 'Provides natural micronutrition', 'Helps in fruit and flower development'],
    usage: { foliar_spray: '5-10 ml per liter of water', drip_irrigation: '10-15 liters per acre' },
    tk: 'RupiyaKuber'
  }],
  [16, {
    n: 'DAP Fertilizer 50kg',
    c: 'Fertilizer',
    tag: 'Crop Nutrition',
    p: 1350,
    r: 4.8,
    rc: 245,
    rec: true,
    stock: true,
    b: 'Bestseller',
    clr: '#1A4D2E',
    img: 'https://agribegri.com/_next/image?url=https%3A%2F%2Fdujjhct8zer0r.cloudfront.net%2Fmedia%2Fprod_image%2F8651509761758697120.webp&w=640&q=90',
    w: '50kg',
    comp: 'Di-ammonium Phosphate (18-46-0)',
    dose: '50-100kg per acre',
    app: 'Soil application at sowing',
    crops: ['Wheat', 'Sugarcane', 'Cotton', 'Rice'],
    season: 'Both',
    d1: 'High quality Di-ammonium Phosphate for strong root establishment.',
    d2: 'Essential for early crop growth and flowering.',
    w1: 'Provides phosphorus essential for root development.',
    w2: 'Helps seedlings establish strongly and improves flowering.',
    longDesc: 'DAP is the most widely used phosphorus fertilizer globally. It is suitable for all crops and soils, providing a high concentration of phosphate and nitrogen.',
    feat: ['Strong root growth', 'Early crop vigor', 'Balanced nitrogen and phosphorus', 'Water soluble phosphate'],
    tk: 'DAP'
  }],
  [17, {
    n: 'Urea 45kg',
    c: 'Fertilizer',
    tag: 'Nitrogen Supply',
    p: 267,
    r: 4.7,
    rc: 412,
    rec: true,
    stock: true,
    b: 'Classic',
    clr: '#1E3A8A',
    img: '/products/auth/urea.jpg',
    w: '45kg',
    comp: 'Urea (46% Nitrogen)',
    dose: '45-90kg per acre',
    app: 'Soil application / Top dressing',
    crops: ['Corn', 'Rice', 'Wheat', 'Vegetables'],
    season: 'Both',
    d1: 'Supplies readily available nitrogen for rapid vegetative growth.',
    d2: 'Produces deep green foliage and boosts overall yield.',
    w1: 'Boosts leafy green growth by supplying readily available nitrogen.',
    w2: 'Essential for photosynthesis and protein production in plants.',
    tk: 'Urea'
  }],
  [18, {
    n: 'Neem Oil Extract 1L',
    c: 'Pesticide',
    tag: 'Organic Protection',
    p: 450,
    r: 4.6,
    rc: 189,
    rec: true,
    stock: true,
    b: 'Organic',
    clr: '#4D7C0F',
    img: 'https://agribegri.com/_next/image?url=https%3A%2F%2Fdujjhct8zer0r.cloudfront.net%2Fmedia%2Fprod_image%2F3507119101755146056.webp&w=750&q=90',
    w: '1L',
    comp: 'Cold Pressed Neem Oil with Azadirachtin',
    dose: '3-5ml per liter of water',
    app: 'Foliar spray',
    crops: ['Tomato', 'Chilli', 'Grapes', 'Vegetables'],
    season: 'Both',
    d1: 'Natural insecticide and repellent that disrupts insect life cycles.',
    d2: 'Safe for beneficial insects and environment-friendly.',
    w1: 'Organic pest repellent that disrupts insect life cycles without harming soil.',
    w2: 'Controls aphids, thrips, and mites naturally.',
    tk: 'NeemOil'
  }],
  [19, {
    n: 'Pioneer Hybrid Corn Seeds 5kg',
    c: 'Seed',
    tag: 'High Yield Hybrid',
    p: 1200,
    r: 4.9,
    rc: 156,
    rec: true,
    stock: true,
    b: 'Premium',
    clr: '#F59E0B',
    img: 'https://pioneer.farm/content/dam/pioneer/farm/global/en/images/Pioneer-Seed-Bag.jpg',
    w: '5kg',
    comp: 'Hybrid Corn F1 Generation',
    dose: '8kg per acre',
    app: 'Sowing at 2.5cm depth',
    crops: ['Corn / Maize'],
    season: 'Kharif / Rabi',
    d1: 'High-yielding hybrid seeds with excellent drought resistance.',
    d2: 'Produces large, uniform grain heads with high test weight.',
    w1: 'Optimized for diverse soil conditions with high germination rate.',
    w2: 'Ensures uniform crop stand and superior yields.',
    tk: 'CornSeeds'
  }],
  [20, {
    n: 'Chlorpyrifos 20% EC 1L',
    c: 'Pesticide',
    tag: 'Broad Spectrum',
    p: 550,
    r: 4.3,
    rc: 124,
    rec: false,
    stock: true,
    clr: '#B91C1C',
    img: 'https://agribegri.com/_next/image?url=https%3A%2F%2Fdujjhct8zer0r.cloudfront.net%2Fmedia%2Fprod_image%2F4259840241753177684.webp&w=750&q=90',
    w: '1L',
    comp: 'Chlorpyrifos 20% EC',
    dose: '2-3ml per liter of water',
    app: 'Foliar spray / Soil drenching',
    crops: ['Cotton', 'Rice', 'Sugarcane', 'Soil Termites'],
    season: 'Both',
    d1: 'Controls a wide range of sucking and chewing pests.',
    d2: 'Excellent for termite control in soil and wooden structures.',
    w1: 'Powerful organophosphate for persistent pest control.',
    w2: 'Highly effective against soil-borne pests and termites.',
    tk: 'Chlorpyrifos'
  }],
  [21, {
    n: 'Vermicompost 50kg',
    c: 'Soil Amendment',
    tag: 'Natural Fertilizer',
    p: 400,
    r: 4.8,
    rc: 98,
    rec: true,
    stock: true,
    b: 'Natural',
    clr: '#78350F',
    img: '/products/auth/vermicompost.jpg',
    w: '50kg',
    comp: 'Earthworm processed organic matter',
    dose: '200-300kg per acre',
    app: 'Soil application',
    crops: ['All Crops', 'Kitchen Gardens', 'Fruits'],
    season: 'Year round',
    d1: 'Rich in organic carbon and essential micronutrients.',
    d2: 'Improves soil structure, aeration, and water retention.',
    w1: 'Enhances soil microbial activity and plant health.',
    w2: 'Provides long-term soil fertility without chemicals.',
    tk: 'Vermicompost'
  }],
  [22, {
    n: 'NPK 19:19:19 1kg',
    c: 'Fertilizer',
    tag: 'Water Soluble',
    p: 180,
    r: 4.6,
    rc: 210,
    rec: true,
    stock: true,
    clr: '#4F46E5',
    img: '/products/auth/npk19.jpg',
    w: '1kg',
    comp: 'Balanced N-P-K (19% each)',
    dose: '5-10g per liter',
    app: 'Foliar spray / Drip',
    crops: ['Vegetables', 'Fruits', 'Flowers', 'Cereals'],
    season: 'Growth Stage',
    d1: 'Completely water-soluble fertilizer for balanced nutrition.',
    d2: 'Promotes vegetative growth, flowering, and fruit development.',
    w1: 'Ideal for rapid nutrient absorption during critical growth stages.',
    w2: 'Ensures even growth and prevents multi-nutrient deficiencies.',
    tk: 'NPK19'
  }],
  [23, {
    n: 'Trichoderma Viride 1kg',
    c: 'Pesticide',
    tag: 'Bio-Fungicide',
    p: 250,
    r: 4.5,
    rc: 87,
    rec: false,
    stock: true,
    clr: '#065F46',
    img: '/products/auth/trichoderma.jpg',
    w: '1kg',
    comp: 'Trichoderma Viride 1.0% WP',
    dose: '4-5g per kg seed / 2kg per acre soil',
    app: 'Seed treatment / Soil application',
    crops: ['Legumes', 'Ginger', 'Turmeric', 'Vegetables'],
    season: 'Both',
    d1: 'Natural antagonist for controlling soil-borne fungal diseases.',
    d2: 'Protects crops from root rot, wilt, and damping-off.',
    w1: 'Eco-friendly biocontrol agent for sustainable farming.',
    w2: 'Promotes root development and plant immunity.',
    tk: 'Trichoderma'
  }],
  [24, {
    n: 'Tomato Seeds (Hybrid) 10g',
    c: 'Seed',
    tag: 'Commercial Variety',
    p: 150,
    r: 4.7,
    rc: 132,
    rec: false,
    stock: true,
    clr: '#DC2626',
    img: '/products/auth/tomato_seeds.png',
    w: '10g',
    comp: 'Hybrid Tomato Seeds',
    dose: '60-80g per acre',
    app: 'Nursery tray sowing',
    crops: ['Tomato'],
    season: 'Kharif / Rabi',
    d1: 'High-yielding hybrid with firm, medium-sized red fruits.',
    d2: 'Tolerant to Leaf Curl Virus and Fusarium wilt.',
    w1: 'Produces uniform fruits suitable for long-distance transport.',
    w2: 'Consistent performer across different climatic zones.',
    tk: 'TomatoSeeds'
  }],
  [25, {
    n: 'MOP (Muriate of Potash) 50kg',
    c: 'Fertilizer',
    tag: 'Potassium Supply',
    p: 850,
    r: 4.4,
    rc: 145,
    rec: false,
    stock: true,
    clr: '#92400E',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0aYnE9Bv3nZ3zZ-nB_k-N_z-b_B_w_t_z-A&s',
    w: '50kg',
    comp: 'Potassium Chloride (60% K2O)',
    dose: '40-60kg per acre',
    app: 'Soil application at sowing/growth',
    crops: ['Sugarcane', 'Potato', 'Grapes', 'Banana'],
    season: 'Both',
    d1: 'Essential for sugar translocation and drought resistance.',
    d2: 'Prevents lodging and improves crop quality and shelf life.',
    w1: 'Prevents lodging and improves drought resistance in crops.',
    w2: 'Crucial for fruit sizing and sugar content.',
    tk: 'MOP'
  }],
  [26, {
    n: 'Imidacloprid 17.8% SL (Confidor)',
    c: 'Pesticide',
    tag: 'Systemic Action',
    p: 320,
    r: 4.7,
    rc: 198,
    rec: true,
    stock: true,
    b: 'Reliable',
    clr: '#3B82F6',
    img: 'https://agribegri.com/_next/image?url=https%3A%2F%2Fdujjhct8zer0r.cloudfront.net%2Fmedia%2Fprod_image%2F7512801971733205868.webp&w=750&q=90',
    w: '250ml',
    comp: 'Imidacloprid 17.8% SL',
    dose: '100-150ml per acre',
    app: 'Foliar spray / Drip',
    crops: ['Chillies', 'Cotton', 'Okra', 'Citrus'],
    season: 'Both',
    d1: 'Reliable systemic insecticide for sucking pest complex.',
    d2: 'Long-lasting control against aphids, thrips, and whiteflies.',
    w1: 'Fast-acting neonicotinoid with excellent translaminar activity.',
    w2: 'Proven protection for high-value horticultural crops.',
    tk: 'ImidaclopridSL'
  }],
  [27, {
    n: 'Gypsum (Agricultural) 50kg',
    c: 'Soil Amendment',
    tag: 'Conditioner',
    p: 350,
    r: 4.2,
    rc: 65,
    rec: false,
    stock: true,
    clr: '#64748B',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0aYnE9Bv3nZ3zZ-nB_k-N_z-b_B_w_t_z-A&s',
    w: '50kg',
    comp: 'Calcium Sulfate Dihydrate',
    dose: '200-500kg per acre',
    app: 'Soil application',
    crops: ['Groundnut', 'Soybean', 'Sodic Soils'],
    season: 'Both',
    d1: 'Reduces soil salinity and improves sodium displacement.',
    d2: 'Rich source of Calcium and Sulfur for improved productivity.',
    w1: 'Reclaims sodic soils and improves water infiltration.',
    w2: 'Essential for groundnut pod filling and oil content.',
    tk: 'Gypsum'
  }]
];

export const storeData = rows.map(([id, cfg]) => make(id, cfg));