import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

import { en } from '../locales/en';
import { hi } from '../locales/hi';
import { gu } from '../locales/gu';

export const translations = {
  EN: {
    ...en,
    lang_en: 'English',
    lang_hi: 'हिन्दी (Hindi)',
    lang_guj: 'ગુજરાતી (Gujarati)',
    'nav.weather': 'Weather',
    'nav.soil_report': 'Soil Report',
    'nav.store': 'AgriStore',
    
    'detect.tag': 'AI-Powered Intelligence',
    'detect.title1': 'Detect Crop Disease ',
    'detect.title2': 'Instantly',
    'detect.desc': 'Upload a clear photo of your affected plant. Our localized AI engine will instantly identify diseases and provide a personalized, actionable treatment plan.',
    'detect.stats': ['✅ High Precision Models', '🌿 Offline Capable Engine', '⚡ Lightning Fast Output'],

    'upload.drop': 'Drop crop photo here',
    'upload.or_select': 'or select using the buttons below',
    'upload.take_photo': 'Take a Photo',
    'upload.upload_gallery': 'Upload Gallery',
    'upload.supports': 'Supports JPG, PNG, WEBP · Max 10MB',
    'upload.tips_title': 'Tips for best results',
    'upload.tip1': 'Good lighting',
    'upload.tip2': 'Close-up of area',
    'upload.tip3': 'Keep camera steady',
    'upload.tip4': 'Include leaves clearly',
    'history.title': 'Your Recent Scans',
    'history.view_all': 'View All',
    'history.no_scans': 'No scans yet — scan your first crop above!',
    'history.healthy': 'Healthy Plant',
    'history.unknown_disease': 'Unknown Disease',
    'history.unknown_crop': 'Unknown Crop',

    'hero.title1': 'किसान की हर ज़रूरत',
    'hero.title2': 'का Digital साथी!',
    'hero.subtitle': 'Empowering Farmers',
    'hero.desc': 'Advanced AI to detect crop diseases in seconds. Reliable, simple, and works right in your palm.',
    'hero.downloadBtn': 'Download Now',
    'hero.scanningActive': 'SCANNING ACTIVE IN',
    'hero.districts': '200+ DISTRICTS',

    'stats.tag': 'Trust Metrics',
    'stats.title': 'Growing Together',
    'stats.items': [
      { number: '10K+', label: 'Active Farmers', value: '10,000+', sublabel: 'Across India' },
      { number: '50K+', label: 'Detections Done', value: '50,000+', sublabel: 'Successful scans' },
      { number: '98%',  label: 'AI Accuracy',     value: '98%',     sublabel: 'Clinically verified' },
      { number: '24/7', label: 'Farmer Support',  value: '24/7',    sublabel: 'Always with you' }
    ],

    'features.tag': 'Key Features',
    'features.title': 'Everything you need',
    'features.desc': 'FasalRakshak brings powerful agricultural AI technology directly to your hands.',
    'features.items': [
      { title: 'Offline Mode', desc: 'No internet? No problem. The app works offline in your fields!' },
      { title: 'Local Languages', desc: 'Get results in your language — Hindi, Gujarati, or English!' },
      { title: '2-Second AI', desc: 'Our AI model identifies diseases in just 2 seconds.' },
      { title: 'Treatment Guide', desc: 'Get clear medicine names, dosage, and application tips.' },
      { title: 'Scan History', desc: 'Review all your past scans and crop health records.' },
      { title: 'Weather Risk', desc: 'Stay updated with local weather risks to your crops.' }
    ],

    'testimonials.tag': 'Farmer Stories',
    'testimonials.title': 'Loved by Farmers',
    'testimonials.desc': 'See how FasalRakshak is changing lives across India.',
    'testimonials.reviews': [
      {
        name: "Rameshbhai Patel", location: "Anand, Gujarat",
        quote: "My groundnut crop was getting destroyed. FasalRakshak identified the disease in just 2 seconds. My crop is saved and I saved a lot of money!",
        cropLabel: "🥜 Groundnut (Mungfali) Farmer"
      },
      {
        name: "Sureshbhai Chauhan", location: "Rajkot, Gujarat",
        quote: "Results in Gujarati — very easy to understand. Medicine name and dosage are all written in the app. Thank you FasalRakshak!",
        cropLabel: "🌿 Cotton (Kapas) Farmer"
      },
      {
        name: "Dineshbhai Desai", location: "Saurashtra, Gujarat",
        quote: "Earlier I had to visit the agriculture center. Now my phone is my crop expert. Very fast and useful app for wheat farmers!",
        cropLabel: "🌾 Wheat (Gehu) Farmer"
      }
    ],

    'how.tag': 'Simple Steps',
    'how.title': 'How to Use FasalRakshak',
    'how.steps': [
      { title: 'Open App', desc: 'Launch the FasalRakshak app on your smartphone.' },
      { title: 'Snap Photo', desc: 'Take a clear picture of the affected crop leaf.' },
      { title: 'Get Results', desc: 'Instantly view disease details and treatment guide.' }
    ],
    'how.supportTag': 'SUPPORTED CROPS',
    'how.supportTitle': 'Crops we currently support',
    'how.crops': [
      { name: '🥜 Groundnut', desc: 'Full lifecycle disease support' },
      { name: '🌾 Wheat', desc: 'Accurate pest & nutrient detection' },
      { name: '☁️ Cotton', desc: 'Early pest attack & disease alerts' }
    ],

    'cta.tag': 'Get Started Free',
    'cta.title': 'Protect Your Harvest Today',
    'cta.desc': 'Join 10,000+ farmers already using FasalRakshak. Free forever, works everywhere.',
    'cta.btn': 'Scan Your Crop Now',
    'cta.comingSoon': 'Coming Soon',

    'footer.subscribeTitle1': 'Join our ',
    'footer.subscribeTitle2': 'Community',
    'footer.subscribeDesc': 'Get weekly organic tips and weather alerts directly in your inbox.',
    'footer.emailPlaceholder': 'Enter your email address',
    'footer.subscribeBtn': 'Join Now',
    'footer.brandDesc': 'FasalRakshak is an AI-powered agriculture companion protecting crops and empowering farmers across India with organic disease detection.',
    'footer.company': 'Company',
    'footer.companyLinks': ['About Us', 'Contact', 'Blog', 'Ecosystem'],
    'footer.solutions': 'Solutions',
    'footer.solutionLinks': ['Disease Detection', 'Weather AI', 'Mandi Prices', 'Soil Health'],
    'footer.contact': 'Contact Us',
    'footer.emailUs': 'Email Support',
    'footer.helpline': 'Helpline Number',
    'footer.tollFree': 'TOLL FREE',
    'footer.headOffice': 'Head Office',
    'footer.address': 'AgriTech Hub, Sector 4, <br/>Gandhinagar, India',
    'footer.copyright': '© {year} FasalRakshak App.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.systemOp': 'SYSTEM ONLINE',

    'soil.manual': '✍️ Manual Entry',
    'soil.upload': '📄 Upload PDF',
    'soil.scan': '📸 Scan Image',
    'login.slogan': 'बेहतर खेती के लिए आपका Digital साथी।',
    'login.googleBtn': 'Google के साथ लॉगिन करें',
    'login.secure': 'SECURE LOGIN',
    'login.free': 'FREE ACCESS',
    'login.trusted': 'TRUSTED BY 10K+ FARMERS',
    'login.designed': 'Designed with ❤️ for the Indian Farmer',
    'login.back': 'Back to Home',

    'store.badge': 'Premium Agri Inputs Store',
    'store.title': 'FasalRakshak',
    'store.titleHighlight': 'Store',
    'store.subtitle': 'Quality pesticides, fertilizers, and crop solutions with direct WhatsApp ordering',
    'store.pesticides': 'Pesticides',
    'store.fertilizers': 'Fertilizers',
    'store.cropProtection': 'Crop Protection',
    'store.growthReg': 'Growth Regulators',
    'store.catalog': 'AgriStore Catalog',
    'store.catalogDesc': 'Real agri inputs with quick WhatsApp ordering',
    'store.cart': 'Cart',
    'store.allCategories': 'All Categories',
    'store.searchPlaceholder': 'Search by product name, crop, or input type',
    'store.maxPrice': 'Max Price',
    'store.starAbove': '4 star and above',
    'store.location': 'Location',
    'store.allLocations': 'All Locations',
    'store.searchResults': 'Search Results',
    'store.allProducts': 'All Products',
    'store.showing': 'Showing',
    'store.of': 'of',
    'store.products': 'products',
    'store.loadMore': 'Load More',
    'store.noProducts': 'No products found',
    'store.noProductsDesc': 'Try adjusting your filters or search terms.',
    'store.clearFilters': 'Clear all filters',
    'store.livePrice': 'Live market prices available',
    'store.dismiss': 'Dismiss',
    'store.addedToCart': 'Added to Cart',
    'store.unsureBuy': '🌿 Unsure what to buy?',
    'store.expertDesc': 'Get instant help from AI or talk to a real expert.',
    'store.askAI': 'Ask AI',
    'store.consultExpert': 'Consult Expert',
    'store.recommended': 'Recommended for your soil 🌱',
    'store.packSize': 'Pack Size',
    'store.price': 'Price',
    'store.inStock': 'In Stock',
    'store.outOfStock': 'Out of Stock',
    'store.addToCart': 'Add to Cart',
    'store.added': 'Added!',
    'store.buyNow': 'Buy Now',
    'store.reviews': 'reviews',
    'store.units': 'units',
    'store.yourCart': 'Your Cart',
    'store.itemsSelected': 'items selected',
    'store.itemSelected': 'item selected',
    'store.subtotal': 'Subtotal',
    'store.total': 'Total',
    'store.clearCart': 'Clear Cart',
    'store.buyAllWhatsapp': 'Buy All on WhatsApp',
    'store.emptyCart': 'Your cart is empty',
    'store.emptyCartDesc': 'Add products from the store and place one combined order on WhatsApp.',
    'store.whyUse': 'Why Use This?',
    'store.keyFeatures': 'Key Features',
    'store.specifications': 'Specifications',
    'store.recommended_crops': 'Recommended Crops',
    'store.usageGuide': 'Usage Guide',
    'store.bestFor': 'Best for',
    'store.season': 'season',
    'store.addedToCartFull': 'Added to Cart!',
    'store.buyOnWhatsapp': 'Buy on WhatsApp',
    'store.contactSeller': 'Contact Seller',
    'store.paymentNote': 'Payment and delivery are coordinated directly with the seller on WhatsApp.',
    'store.productOverview': 'Product Overview',
    'store.composition': 'Composition',
    'store.weight': 'Weight',
    'store.dosage': 'Dosage',
    'store.application': 'Application Method',
    'disease.severe': 'Severe',
    'disease.moderate': 'Moderate',
    'disease.mild': 'Mild',
    'disease.fungal': 'Fungal',
    'disease.bacterial': 'Bacterial',
    'disease.viral': 'Viral',
    'disease.pest': 'Pest',
    'disease.nutrient': 'Nutrient',
    'disease.spreads_fast': 'Spreads Fast',
    'disease.gujarat': 'Gujarat',
    'disease.aka': 'aka',
    'disease.more_symptoms': 'more symptoms',
    'disease.view_details': 'View Details',
    'disease.search_placeholder': 'Search crop diseases, symptoms, or local names...',
    'disease.all_crops': 'All Crops',
    'disease.clear_filters': 'Clear All Filters',
    'disease.active_filters': 'Active',
    'disease.symptoms': 'Symptoms',
    'disease.causes': 'What Causes This Disease?',
    'disease.weather_conditions': 'Weather Conditions',
    'disease.treatment_plan': 'Treatment Plan',
    'disease.organic_alternative': 'Organic / Natural Alternative',
    'disease.how_to_prevent': 'How to Prevent',
    'disease.first_aid_tip': 'First Aid Tip',
    'disease.affected_states': 'Most Affected States',
    'disease.quick_actions': 'Quick Actions',
    'disease.scan_my_crop': 'Scan My Crop',
    'disease.share_whatsapp': 'Share on WhatsApp',
    'disease.copy_treatment': 'Copy Treatment Steps',
    'disease.at_a_glance': 'At a Glance',
    'disease.crop': 'Crop',
    'disease.type': 'Type',
    'disease.severity': 'Severity',
    'disease.spreads': 'Spreads',
    'disease.season': 'Season',
    'disease.yield_loss': 'Yield Loss',
    'disease.contagious': 'Contagious',
    'disease.similar_diseases': 'Similar Diseases',
    'disease.other_diseases': 'Other Diseases',
    'disease.no_diseases': 'No diseases found',
    'disease.try_different': 'Try searching with different keywords or clear your filters',
    'disease.affected_parts': 'Affected Parts',
    'disease.leaf': 'Leaf',
    'disease.stem': 'Stem',
    'disease.root': 'Root',
    'disease.fruit': 'Fruit',
    'disease.flower': 'Flower',
    'weather.title': 'Agri-Weather Center',
    'weather.locating': 'Locating field...',
    'weather.search_placeholder': 'Search village or city...',
    'weather.detect_location': 'Detect Live Location',
    'weather.syncing': 'Syncing with Weather Satellites...',
    'weather.current_temp': 'Current Temp',
    'weather.soil_humidity': 'Soil Humidity',
    'weather.wind_speed': 'Wind Speed',
    'weather.rain_prob': 'Rain Probability',
    'weather.air_soil_sat': 'Air-Soil Saturation',
    'weather.avg_wind': 'Avg Current Speed',
    'weather.precip_risk': 'Precipitation Risk',
    'weather.radar_title': 'Interactive Agricultural Radar',
    'weather.windy_title': 'Windy Global Visualization',
    'weather.satellite_mode': 'Satellite (Interactive)',
    'weather.windy_mode': 'Windy (Visuals)',
    'weather.wind_animation_note': 'Wind Animation Mode (Non-interactive)',
    'weather.ai_advice_title': 'AI Intelligence Advice',
    'weather.irrigation_log': 'Irrigation Log',
    'weather.climate_trends': 'Climate Trends (7-Day)',
    'weather.temp_unit': 'Temperature (°C)',
    'weather.rain_unit': 'Rain Prob (%)',
    'weather.clear': 'Clear sky',
    'weather.sunny': 'Sunny',
    'weather.p_cloudy': 'Partly cloudy',
    'weather.cloudy': 'Cloudy',
    'weather.foggy': 'Foggy',
    'weather.rainy': 'Rainy',
    'weather.showers': 'Showers',
    'weather.storm': 'Thunderstorm',
    'weather.advice_humidity': 'Very high humidity. Risk of Leaf Rust disease.',
    'weather.advice_rain': 'High rain probability. Do not apply solid fertilizers.',
    'weather.advice_heat': 'Critical heatwave warning. Double irrigation immediately.',
    'weather.advice_wind': 'Strong winds detected. Secure tall plants.',
    'weather.advice_optimal': 'Optimal agricultural conditions today.',
    'weather.irrigation_heavy_rain': '⚠️ Heavy rain detected. Pause irrigation for next 24 hours to prevent soil erosion.',
    'weather.irrigation_clear': '✅ Clear skies. Proceed with standard irrigation cycles between 6:00 AM - 9:00 AM.',
    'weather.location_verified': 'Location Verified',
    'weather.current_selection': 'Current Selection',
    'weather.fetch_failed': 'Failed to fetch weather for this location.'
  },
  HI: {
    ...hi,
    lang_en: 'English',
    lang_hi: 'हिन्दी (Hindi)',
    lang_guj: 'ગુજરાતી (Gujarati)',
    'nav.weather': 'मौसम',
    'nav.soil_report': 'मृदा रिपोर्ट',
    'nav.store': 'कृषि स्टोर',
    
    'detect.tag': 'एआई-संचालित बुद्धिमत्ता',
    'detect.title1': 'फसल की बीमारी का ',
    'detect.title2': 'तुरंत पता लगाएं',
    'detect.desc': 'अपने प्रभावित पौधे की एक साफ फोटो अपलोड करें। हमारा एआई इंजन तुरंत बीमारी की पहचान करेगा और एक सटीक उपचार योजना प्रदान करेगा।',
    'detect.stats': ['✅ उच्च सटीकता मॉडल', '🌿 ऑफलाइन सक्षम इंजन', '⚡ तेज़ परिणाम'],

    'upload.drop': 'फसल की फोटो यहाँ डालें',
    'upload.or_select': 'या नीचे दिए गए बटन का उपयोग करें',
    'upload.take_photo': 'तस्वीर खींचें',
    'upload.upload_gallery': 'गैलरी से अपलोड करें',
    'upload.supports': 'सपोर्ट: JPG, PNG, WEBP · अधिकतम 10MB',
    'upload.tips_title': 'बेहतर परिणाम के लिए टिप्स',
    'upload.tip1': 'अच्छी रोशनी',
    'upload.tip2': 'नज़दीक से फोटो लें',
    'upload.tip3': 'कैमरा स्थिर रखें',
    'upload.tip4': 'पत्ते साफ दिखने चाहिए',
    'history.title': 'आपके हालिया स्कैन',
    'history.view_all': 'सभी देखें',
    'history.no_scans': 'अभी तक कोई स्कैन नहीं — ऊपर अपनी पहली फसल स्कैन करें!',
    'history.healthy': 'स्वस्थ पौधा',
    'history.unknown_disease': 'अज्ञात बीमारी',
    'history.unknown_crop': 'अज्ञात फसल',

    'hero.title1': 'किसान की हर ज़रूरत',
    'hero.title2': 'का Digital साथी!',
    'hero.subtitle': 'Empowering Farmers',
    'hero.desc': 'सेकंडों में फसल की बीमारियों को पहचानने के लिए उन्नत एआई। भरोसेमंद और आपके हाथ में।',
    'hero.downloadBtn': 'Download Now',
    'hero.scanningActive': 'SCANNING ACTIVE IN',
    'hero.districts': '200+ जिलों में',

    'stats.tag': 'भरोसा',
    'stats.title': 'साथ मिलकर आगे बढ़ें',
    'stats.items': [
      { number: '10K+', label: 'सक्रिय किसान', value: '10K+', sublabel: 'पूरे भारत में' },
      { number: '50K+', label: 'सफल पहचान', value: '50K+', sublabel: 'सफल स्कैन' },
      { number: '98%',  label: 'एआई सटीकता', value: '98%',  sublabel: 'क्लिनिकली प्रमाणित' },
      { number: '24/7', label: 'किसान सहायता', value: '24/7', sublabel: 'हमेशा आपके साथ' }
    ],

    'features.tag': 'मुख्य विशेषताएं',
    'features.title': 'वह सब कुछ जो आपको चाहिए',
    'features.desc': 'फसलरक्षक सीधे आपके हाथों में शक्तिशाली कृषि एआई तकनीक लाता है।',
    'features.items': [
      { title: 'ऑफलाइन मोड', desc: 'इंटरनेट नहीं? कोई बात नहीं। ऐप खेत में भी काम करता है!' },
      { title: 'स्थानीय भाषाएं', desc: 'अपनी भाषा में परिणाम प्राप्त करें — हिन्दी, गुजराती या अंग्रेजी!' },
      { title: '2-सेकंड एआई', desc: 'हमारा एआई मॉडल सिर्फ 2 सेकंड में बीमारी पहचान लेता है।' },
      { title: 'उपचार गाइड', desc: 'दवाई का नाम, मात्रा और उपयोग के तरीके जानें।' },
      { title: 'स्कैन इतिहास', desc: 'अपने पुराने सभी स्कैन और फसल स्वास्थ्य रिकॉर्ड देखें।' },
      { title: 'मौसम जोखिम', desc: 'अपनी फसलों के लिए स्थानीय मौसम जोखिमों से अपडेट रहें।' }
    ],

    'testimonials.tag': 'किसान की कहानियाँ',
    'testimonials.title': 'किसानों की पसंद',
    'testimonials.desc': 'देखें कैसे फसलरक्षक पूरे भारत में किसानों की ज़िंदगी बदल रहा है।',
    'testimonials.reviews': [
      {
        name: "रमेशभाई पटेल", location: "आणंद, गुजरात",
        quote: "मेरी मूंगफली की फसल खराब हो रही थी। फसलरक्षक ने सिर्फ 2 सेकंड में बीमारी पहचान ली। मेरी फसल भी बच गई और काफी पैसे भी बचे!",
        cropLabel: "🥜 मूंगफली किसान"
      },
      {
        name: "सुरेशभाई चौहान", location: "राजकोट, गुजरात",
        quote: "गुजराती में परिणाम — समझने में बहुत आसान। दवाई का नाम और मात्रा सब ऐप में लिखी होती है। फसलरक्षक का धन्यवाद!",
        cropLabel: "🌿 कपास किसान"
      },
      {
        name: "दिनेशभाई देसाई", location: "सौराष्ट्र, गुजरात",
        quote: "पहले मुझे कृषि केंद्र जाना पड़ता था। अब मेरा फोन ही मेरा फसल विशेषज्ञ है। गेहूं के किसानों के लिए बहुत तेज़ और उपयोगी ऐप!",
        cropLabel: "🌾 गेहूं किसान"
      }
    ],

    'how.tag': 'आसान चरण',
    'how.title': 'उपयोग कैसे करें',
    'how.steps': [
      { title: 'ऐप खोलें', desc: 'स्मार्टफोन पर फसलरक्षक ऐप लॉन्च करें।' },
      { title: 'फोटो लें', desc: 'प्रभावित फसल के पत्ते की साफ फोटो लें।' },
      { title: 'परिणाम पाएं', desc: 'बीमारी का विवरण और उपचार गाइड तुरंत देखें।' }
    ],
    'how.supportTag': 'समर्थित फसलें',
    'how.supportTitle': 'फसलें जिनका हम समर्थन करते हैं',
    'how.crops': [
      { name: '🥜 मूंगफली', desc: 'संपूर्ण जीवनचक्र बीमारी समर्थन' },
      { name: '🌾 गेहूं', desc: 'सटीक कीट और पोषक तत्वों की पहचान' },
      { name: '☁️ कपास', desc: 'कीट हमले और बीमारी की प्रारंभिक चेतावनी' }
    ],

    'cta.tag': 'निशुल्क शुरू करें',
    'cta.title': 'आज ही अपनी फसल सुरक्षित करें',
    'cta.desc': 'फसलरक्षक का उपयोग करने वाले 10,000+ किसानों में शामिल हों। हमेशा के लिए मुक्त।',
    'cta.btn': 'अभी स्कैन करें',
    'cta.comingSoon': 'कमिंग सून',

    'footer.subscribeTitle1': 'हमारे ',
    'footer.subscribeTitle2': 'समुदाय से जुड़ें',
    'footer.subscribeDesc': 'साप्ताहिक जैविक सुझाव और मौसम अलर्ट सीधे अपने इनबॉक्स में प्राप्त करें।',
    'footer.emailPlaceholder': 'अपना ईमेल पता दर्ज करें',
    'footer.subscribeBtn': 'अभी जुड़ें',
    'footer.brandDesc': 'फसलरक्षक एक एआई-संचालित कृषि साथी है जो जैविक रोग पहचान के साथ पूरे भारत में फसलों की रक्षा और किसानों को सशक्त बनाता है।',
    'footer.company': 'कंपनी',
    'footer.companyLinks': ['हमारे बारे में', 'संपर्क करें', 'ब्लॉग', 'इकोसिस्टम'],
    'footer.solutions': 'समाधान',
    'footer.solutionLinks': ['बीमारी की पहचान', 'मौसम एआई', 'मंडी भाव', 'मिट्टी स्वास्थ्य'],
    'footer.contact': 'हमसे संपर्क करें',
    'footer.emailUs': 'ईमेल सहायता',
    'footer.helpline': 'हेल्पलाइन नंबर',
    'footer.tollFree': 'टोल फ्री',
    'footer.headOffice': 'मुख्य कार्यालय',
    'footer.address': 'एग्रीटेक हब, सेक्टर 4, <br/>गांधीनगर, भारत',
    'footer.copyright': '© {year} फसलरक्षक ऐप।',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'शर्तें एवं नियम',
    'footer.systemOp': 'सिस्टम ऑनलाइन है',

    'soil.manual': '✍️ मैनुअल एंट्री',
    'soil.upload': '📄 PDF अपलोड',
    'soil.scan': '📸 इमेज स्कैन',
    'login.slogan': 'बेहतर खेती के लिए आपका Digital साथी।',
    'login.googleBtn': 'Google के साथ लॉगिन करें',
    'login.secure': 'सुरक्षित लॉगिन',
    'login.free': 'मुफ्त एक्सेस',
    'login.trusted': '10,000+ किसानों का भरोसा',
    'login.designed': 'भारतीय किसानों के लिए ❤️ के साथ डिज़ाइन किया गया',
    'login.back': 'मुख्य पृष्ठ पर वापस',

    'store.badge': 'प्रीमियम कृषि इनपुट स्टोर',
    'store.title': 'फसलरक्षक',
    'store.titleHighlight': 'स्टोर',
    'store.subtitle': 'सीधे WhatsApp ऑर्डरिंग के साथ गुणवत्तापूर्ण कीटनाशक, उर्वरक, और फसल समाधान',
    'store.pesticides': 'कीटनाशक',
    'store.fertilizers': 'उर्वरक',
    'store.cropProtection': 'फसल सुरक्षा',
    'store.growthReg': 'वृद्धि नियामक',
    'store.catalog': 'एग्रीस्टोर कैटलॉग',
    'store.catalogDesc': 'WhatsApp से त्वरित ऑर्डरिंग के साथ असली कृषि इनपुट',
    'store.cart': 'कार्ट',
    'store.allCategories': 'सभी श्रेणियाँ',
    'store.searchPlaceholder': 'उत्पाद नाम, फसल, या इनपुट प्रकार से खोजें',
    'store.maxPrice': 'अधिकतम कीमत',
    'store.starAbove': '4 स्टार और ऊपर',
    'store.location': 'स्थान',
    'store.allLocations': 'सभी स्थान',
    'store.searchResults': 'खोज परिणाम',
    'store.allProducts': 'सभी उत्पाद',
    'store.showing': 'दिखाया जा रहा है',
    'store.of': 'में से',
    'store.products': 'उत्पाद',
    'store.loadMore': 'और लोड करें',
    'store.noProducts': 'कोई उत्पाद नहीं मिला',
    'store.noProductsDesc': 'अपने फ़िल्टर या खोज शब्द बदलकर देखें।',
    'store.clearFilters': 'सभी फ़िल्टर हटाएं',
    'store.livePrice': 'लाइव बाज़ार कीमतें उपलब्ध',
    'store.dismiss': 'बंद करें',
    'store.addedToCart': 'कार्ट में जोड़ा',
    'store.unsureBuy': '🌿 क्या खरीदें यह पता नहीं?',
    'store.expertDesc': 'AI से तुरंत मदद लें या किसी विशेषज्ञ से बात करें।',
    'store.askAI': 'AI से पूछें',
    'store.consultExpert': 'विशेषज्ञ से परामर्श',
    'store.recommended': 'आपकी मिट्टी के लिए अनुशंसित 🌱',
    'store.packSize': 'पैक साइज़',
    'store.price': 'कीमत',
    'store.inStock': 'उपलब्ध',
    'store.outOfStock': 'उपलब्ध नहीं',
    'store.addToCart': 'कार्ट में डालें',
    'store.added': 'जोड़ा!',
    'store.buyNow': 'अभी खरीदें',
    'store.reviews': 'समीक्षाएं',
    'store.units': 'यूनिट',
    'store.yourCart': 'आपकी कार्ट',
    'store.itemsSelected': 'आइटम चुने गए',
    'store.itemSelected': 'आइटम चुना गया',
    'store.subtotal': 'उप-कुल',
    'store.total': 'कुल',
    'store.clearCart': 'कार्ट खाली करें',
    'store.buyAllWhatsapp': 'WhatsApp पर सब खरीदें',
    'store.emptyCart': 'आपकी कार्ट खाली है',
    'store.emptyCartDesc': 'स्टोर से उत्पाद जोड़ें और WhatsApp पर एक साथ ऑर्डर करें।',
    'store.whyUse': 'यह क्यों उपयोग करें?',
    'store.keyFeatures': 'मुख्य विशेषताएं',
    'store.specifications': 'विशिष्टताएं',
    'store.recommended_crops': 'अनुशंसित फसलें',
    'store.usageGuide': 'उपयोग गाइड',
    'store.bestFor': 'के लिए सर्वोत्तम',
    'store.season': 'मौसम',
    'store.addedToCartFull': 'कार्ट में जोड़ा!',
    'store.buyOnWhatsapp': 'WhatsApp पर खरीदें',
    'store.contactSeller': 'विक्रेता से संपर्क करें',
    'store.paymentNote': 'भुगतान और डिलीवरी WhatsApp पर सीधे विक्रेता के साथ होती है।',
    'store.productOverview': 'उत्पाद अवलोकन',
    'store.composition': 'संरचना',
    'store.weight': 'वज़न',
    'store.dosage': 'खुराक',
    'store.application': 'प्रयोग करने का तरीका',
    'disease.severe': 'गंभीर',
    'disease.moderate': 'मध्यम',
    'disease.mild': 'हल्का',
    'disease.fungal': 'कवक (Fungal)',
    'disease.bacterial': 'जीवाणु (Bacterial)',
    'disease.viral': 'वायरल (Viral)',
    'disease.pest': 'कीट (Pest)',
    'disease.nutrient': 'पोषक तत्व (Nutrient)',
    'disease.spreads_fast': 'तेज़ी से फैलता है',
    'disease.gujarat': 'गुजरात',
    'disease.aka': 'जिसे भी कहते हैं',
    'disease.more_symptoms': 'और लक्षण',
    'disease.view_details': 'विवरण देखें',
    'disease.search_placeholder': 'फसल रोग, लक्षण या स्थानीय नाम खोजें...',
    'disease.all_crops': 'सभी फसलें',
    'disease.clear_filters': 'सभी फ़िल्टर हटाएं',
    'disease.active_filters': 'सक्रिय',
    'disease.symptoms': 'लक्षण',
    'disease.causes': 'यह रोग क्यों होता है?',
    'disease.weather_conditions': 'मौसम की स्थिति',
    'disease.treatment_plan': 'उपचार योजना',
    'disease.organic_alternative': 'जैविक / प्राकृतिक विकल्प',
    'disease.how_to_prevent': 'बचाव कैसे करें',
    'disease.first_aid_tip': 'प्राथमिक उपचार',
    'disease.affected_states': 'सबसे प्रभावित राज्य',
    'disease.quick_actions': 'त्वरित कार्रवाई',
    'disease.scan_my_crop': 'मेरी फसल स्कैन करें',
    'disease.share_whatsapp': 'WhatsApp पर शेयर करें',
    'disease.copy_treatment': 'उपचार के चरण कॉपी करें',
    'disease.at_a_glance': 'एक नज़र में',
    'disease.crop': 'फसल',
    'disease.type': 'प्रकार',
    'disease.severity': 'गंभीरता',
    'disease.spreads': 'फैलाव',
    'disease.season': 'मौसम',
    'disease.yield_loss': 'पैदावार में नुकसान',
    'disease.contagious': 'संक्रामक',
    'disease.similar_diseases': 'मिलते-जुलते रोग',
    'disease.other_diseases': 'अन्य रोग',
    'disease.no_diseases': 'कोई रोग नहीं मिला',
    'disease.try_different': 'अलग शब्दों से खोजें या फ़िल्टर हटाएं',
    'disease.affected_parts': 'प्रभावित हिस्से',
    'disease.leaf': 'पत्ती',
    'disease.stem': 'तना',
    'disease.root': 'जड़',
    'disease.fruit': 'फल',
    'disease.flower': 'फूल',
    'weather.title': 'कृषि-मौसम केंद्र',
    'weather.locating': 'खेत का स्थान खोजा जा रहा है...',
    'weather.search_placeholder': 'गाँव या शहर खोजें...',
    'weather.detect_location': 'लाइव स्थान का पता लगाएं',
    'weather.syncing': 'मौसम उपग्रहों के साथ समन्वय किया जा रहा है...',
    'weather.current_temp': 'वर्तमान तापमान',
    'weather.soil_humidity': 'मिट्टी की नमी',
    'weather.wind_speed': 'हवा की गति',
    'weather.rain_prob': 'बारिश की संभावना',
    'weather.air_soil_sat': 'वायु-मृदा संतृप्ति',
    'weather.avg_wind': 'औसत वर्तमान गति',
    'weather.precip_risk': 'वर्षा का जोखिम',
    'weather.radar_title': 'इंटरएक्टिव कृषि रडार',
    'weather.windy_title': 'विंडी ग्लोबल विज़ुअलाइज़ेशन',
    'weather.satellite_mode': 'सैटेलाइट (इंटरएक्टिव)',
    'weather.windy_mode': 'विंडी (दृश्य)',
    'weather.wind_animation_note': 'विंड एनीमेशन मोड (केवल देखने के लिए)',
    'weather.ai_advice_title': 'AI इंटेलिजेंस सलाह',
    'weather.irrigation_log': 'सिंचाई लॉग',
    'weather.climate_trends': 'जलवायु रुझान (7-दिन)',
    'weather.temp_unit': 'तापमान (°C)',
    'weather.rain_unit': 'बारिश संभावना (%)',
    'weather.clear': 'साफ आकाश',
    'weather.sunny': 'धूप',
    'weather.p_cloudy': 'आंशिक रूप से बादल',
    'weather.cloudy': 'बादल छाए रहेंगे',
    'weather.foggy': 'धुंधला',
    'weather.rainy': 'बारिश',
    'weather.showers': 'बौछारें',
    'weather.storm': 'आंधी-तूफान',
    'weather.advice_humidity': 'बहुत अधिक उमस। लीफ रस्ट रोग का खतरा।',
    'weather.advice_rain': 'भारी बारिश की संभावना। ठोस खाद न डालें।',
    'weather.advice_heat': 'भीषण लू की चेतावनी। तुरंत दोगुनी सिंचाई करें।',
    'weather.advice_wind': 'तेज़ हवाएँ। ऊंचे पौधों को सहारा दें।',
    'weather.advice_optimal': 'आज खेती के लिए अनुकूल परिस्थितियां हैं।',
    'weather.irrigation_heavy_rain': '⚠️ भारी बारिश का पता चला। मिट्टी के कटाव को रोकने के लिए अगले 24 घंटों के लिए सिंचाई रोक दें।',
    'weather.irrigation_clear': '✅ साफ आसमान। सुबह 6:00 से 9:00 बजे के बीच सामान्य सिंचाई करें।',
    'weather.location_verified': 'स्थान सत्यापित',
    'weather.current_selection': 'वर्तमान चयन',
    'weather.fetch_failed': 'इस स्थान की मौसम जानकारी नहीं मिली।'
  },
  GUJ: {
    ...gu,
    lang_en: 'English',
    lang_hi: 'हिन्दी (Hindi)',
    lang_guj: 'ગુજરાતી (Gujarati)',
    'nav.home': 'મુખ્ય',
    'nav.detect': 'ખોડ શોધો',
    'nav.library': 'લાઈબ્રેરી',
    'nav.weather': 'હવામાન',
    'nav.blog': 'બ્લોગ',
    'nav.about': 'અમારા વિશે',
    'nav.contact': 'સંપર્ક',
    'nav.login': 'લૉગિન',
    'nav.soil_report': 'જમીન રિપોર્ટ',
    'nav.store': 'કૃષિ દુકાન',
    
    'detect.tag': 'AI-સંચાલિત બુદ્ધિમત્તા',
    'detect.title1': 'પાકના રોગની ',
    'detect.title2': 'તરત જ તપાસ કરો',
    'detect.desc': 'તમારા રોગગ્રસ્ત છોડનો સ્પષ્ટ ફોટો અપલોડ કરો. અમારું AI એન્જિન તરત જ રોગની ઓળખ કરશે અને ચોક્કસ સારવાર યોજના આપશે.',
    'detect.stats': ['✅ ઉચ્ચ ચોકસાઈ મોડેલ્સ', '🌿 ઑફલાઇન સક્ષમ એન્જિન', '⚡ અતિ ઝડપી પરિણામ'],

    'upload.drop': 'પાકનો ફોટો અહીં છોડો',
    'upload.or_select': 'અથવા નીચેના બટનોનો ઉપયોગ કરો',
    'upload.take_photo': 'ફોટો પાડો',
    'upload.upload_gallery': 'ગેલેરીમાંથી અપલોડ કરો',
    'upload.supports': 'સપોર્ટ: JPG, PNG, WEBP · મહત્તમ 10MB',
    'upload.tips_title': 'સારા પરિણામો માટે ટિપ્સ',
    'upload.tip1': 'સારો પ્રકાશ',
    'upload.tip2': 'નજીકથી ફોટો લો',
    'upload.tip3': 'કેમેરો સ્થિર રાખો',
    'upload.tip4': 'પાંદડા ચોખ્ખા દેખાવા જોઈએ',
    'history.title': 'તમારા તાજેતરના સ્કેન',
    'history.view_all': 'બધા જુઓ',
    'history.no_scans': 'હજુ સુધી કોઈ સ્કેન નથી — ઉપર તમારો પહેલો પાક સ્કેન કરો!',
    'history.healthy': 'તંદુરસ્ત છોડ',
    'history.unknown_disease': 'અજ્ઞાત રોગ',
    'history.unknown_crop': 'અજ્ઞાત પાક',

    'hero.title1': 'ખેડૂતની દરેક જરૂરિયાતનો',
    'hero.title2': 'Digital સાથી!',
    'hero.subtitle': 'ખેડૂતોનું સશક્તિકરણ',
    'hero.desc': 'થોડી જ સેકન્ડોમાં પાકના રોગોને ઓળખવા માટે અત્યાધુનિક AI. વિશ્વાસપાત્ર, સરળ અને તમારા હાથમાં કામ કરે છે.',
    'hero.downloadBtn': 'હમણાં ડાઉનલોડ કરો',
    'hero.scanningActive': 'સ્કેનિંગ સક્રિય છે',
    'hero.districts': '200+ જિલ્લાઓમાં',

    'stats.tag': 'વિશ્વાસ',
    'stats.title': 'સાથે મળીને આગળ વધીએ',
    'stats.items': [
      { number: '10K+', label: 'સક્રિય ખેડૂતો', value: '10K+', sublabel: 'સમગ્ર ભારતમાં' },
      { number: '50K+', label: 'સફળ ઓળખ', value: '50K+', sublabel: 'સફળ સ્કેન' },
      { number: '98%',  label: 'AI ચોકસાઈ', value: '98%',  sublabel: 'ક્લિનિકલી પ્રમાણિત' },
      { number: '24/7', label: 'ખેડૂત સહાય', value: '24/7', sublabel: 'હંમેશા તમારી સાથે' }
    ],

    'features.tag': 'મુખ્ય વિશેષતાઓ',
    'features.title': 'તમારે જે બધું જોઈએ છે તે',
    'features.desc': 'ફસલરક્ષક સીધી તમારા હાથમાં શક્તિશાળી કૃષિ AI ટેકનોલોજી લાવે છે.',
    'features.items': [
      { title: 'ઓફલાઇન મોડ', desc: 'ઇન્ટરનેટ નથી? કોઈ વાંધો નહીં. એપ તમારા ખેતરમાં પણ કામ કરે છે!' },
      { title: 'સ્થાનિક ભાષાઓ', desc: 'તમારી ભાષામાં પરિણામો મેળવો - ગુજરાતી, હિન્દી કે અંગ્રેજી!' },
      { title: '2-સેકન્ડ AI', desc: 'અમારું AI મોડેલ પાકનો રોગ માત્ર 2 સેકન્ડમાં ઓળખી લે છે.' },
      { title: 'સારવાર માર્ગદર્શિકા', desc: 'દવાના નામ, માત્રા અને ઉપયોગની પદ્ધતિઓ વિશે જાણો.' },
      { title: 'સ્કેન હિસ્ટ્રી', desc: 'તમારા અગાઉના તમામ સ્કેન અને પાકના સ્વાસ્થ્યના રેકોર્ડ જુઓ.' },
      { title: 'હવામાન જોખમ', desc: 'તમારા પાક માટે સ્થાનિક હવામાનના જોખમો વિશે અપડેટ રહો.' }
    ],

    'testimonials.tag': 'ખેડૂતોની વાર્તાઓ',
    'testimonials.title': 'ખેડૂતોની પસંદ',
    'testimonials.desc': 'જુઓ ફસલરક્ષક સમગ્ર ભારતમાં ખેડૂતોનું જીવન કેવી રીતે બદલી રહ્યું છે.',
    'testimonials.reviews': [
      {
        name: "રમેશભાઈ પટેલ", location: "આણંદ, ગુજરાત",
        quote: "મારો મગફળીનો પાક બગડી રહ્યો હતો. ફસલરક્ષકે 2 સેકન્ડમાં રોગ ઓળખી કાઢ્યો. મારો પાક પણ બચી ગયો અને મારા ઘણા પૈસા પણ બચ્યા!",
        cropLabel: "🥜 મગફળીના ખેડૂત"
      },
      {
        name: "સુરેશભાઈ ચૌહાણ", location: "રાજકોટ, ગુજરાત",
        quote: "ગુજરાતીમાં પરિણામ — સમજવામાં ખૂબ જ સરળ. દવાનું નામ અને ડોઝ એપમાં જ લખેલું હોય છે. ફસલરક્ષકનો આભાર!",
        cropLabel: "🌿 કપાસના ખેડૂત"
      },
      {
        name: "દિનેશભાઈ દેસાઈ", location: "સૌરાષ્ટ્ર, ગુજરાત",
        quote: "પહેલા મારે કૃષિ કેન્દ્ર જવું પડતું હતું. હવે મારો ફોન જ મારો પાક નિષ્ણાત છે. ઘઉંના ખેડૂતો માટે ખૂબ જ ઝડપી અને ઉપયોગી એપ!",
        cropLabel: "🌾 ઘઉંના ખેડૂત"
      }
    ],

    'how.tag': 'સરળ પગલાં',
    'how.title': 'ફસલરક્ષકનો ઉપયોગ કેવી રીતે કરવો',
    'how.steps': [
      { title: 'એપ ખોલો', desc: 'તમારા સ્માર્ટફોન પર ફસલરક્ષક એપ ચાલુ કરો.' },
      { title: 'ફોટો લો', desc: 'રોગગ્રસ્ત પાકના પાંદડાનો સ્પષ્ટ ફોટો લો.' },
      { title: 'પરિણામ મેળવો', desc: 'રોગની વિગત અને સારવાર માર્ગદર્શિકા તરત જુઓ.' }
    ],
    'how.supportTag': 'સપોર્ટ કરાયેલા પાક',
    'how.supportTitle': 'અમે હાલમાં આ પાકોને સપોર્ટ કરીએ છીએ',
    'how.crops': [
      { name: '🥜 મગફળી', desc: 'સંપૂર્ણ જીવનચક્ર રોગ સપોર્ટ' },
      { name: '🌾 ઘઉં', desc: 'ચોક્કસ જીવાત અને પોષક તત્વોની ઓળખ' },
      { name: '☁️ કપાસ', desc: 'જીવાતોના હુમલા અને રોગની પ્રારંભિક ચેતવણી' }
    ],

    'cta.tag': 'નિઃશુલ્ક શરૂ કરો',
    'cta.title': 'આજે જ તમારા પાકને સુરક્ષિત કરો',
    'cta.desc': 'ફસલરક્ષકનો ઉપયોગ કરતા 10,000+ ખેડૂતોમાં જોડાઓ. હંમેશા માટે મફત.',
    'cta.btn': 'અત્યારે જ સ્કેન કરો',
    'cta.comingSoon': 'ટૂંક સમયમાં આવી રહ્યું છે',

    'footer.subscribeTitle1': 'અમારા ',
    'footer.subscribeTitle2': 'સમુદાયમાં જોડાઓ',
    'footer.subscribeDesc': 'તમારા ઇનબોક્સમાં સીધી સાપ્તાહિક જૈવિક ટિપ્સ અને હવામાન ચેતવણીઓ મેળવો.',
    'footer.emailPlaceholder': 'તમારું ઇમેઇલ સરનામું દાખલ કરો',
    'footer.subscribeBtn': 'હમણાં જોડાઓ',
    'footer.brandDesc': 'ફસલરક્ષક એ AI સંચાલિત કૃષિ સાથી છે જે જૈવિક રોગની ઓળખ સાથે સમગ્ર ભારતમાં પાકનું રક્ષણ કરે છે અને ખેડૂતોને સશક્ત બનાવે છે.',
    'footer.company': 'કંપની',
    'footer.companyLinks': ['અમારા વિશે', 'સંપર્ક કરો', 'બ્લોગ', 'ઇકોસિસ્ટમ'],
    'footer.solutions': 'ઉકેલો',
    'footer.solutionLinks': ['રોગની ઓળખ', 'હવામાન AI', 'મંડી ભાવ', 'જમીન સ્વાસ્થ્ય'],
    'footer.contact': 'અમારો સંપર્ક કરો',
    'footer.emailUs': 'ઇમેઇલ સહાય',
    'footer.helpline': 'હેલ્પલાઇન નંબર',
    'footer.tollFree': 'ટોલ ફ્રી',
    'footer.headOffice': 'મુખ્ય કાર્યાલય',
    'footer.address': 'એગ્રીટેક હબ, સેક્ટર 4, <br/>ગાંધીનગર, ભારત',
    'footer.copyright': '© {year} ફસલરક્ષક એપ.',
    'footer.privacy': 'ગોપનીયતા નીતિ',
    'footer.terms': 'નિયમો અને શરતો',
    'footer.systemOp': 'સિસ્ટમ ઓનલાઇન છે',

    'soil.manual': '✍️ મેન્યુઅલ એન્ટ્રી',
    'soil.upload': '📄 PDF અપલોડ',
    'soil.scan': '📸 ફોટો સ્કેન',

    'login.slogan': 'વધુ સારી ખેતી માટે તમારો Digital સાથી.',
    'login.googleBtn': 'Google સાથે લૉગિન કરો',
    'soil.manual': '✍️ મેન્યુઅલ એન્ટ્રી',
    'soil.upload': '📄 PDF અપલોડ',
    'soil.scan': '📸 ફોટો સ્કેન',
    'login.secure': 'સુરક્ષિત લૉગિન',
    'login.free': 'મફત ઉપયોગ',
    'login.trusted': '10,000+ ખેડૂતોનો વિશ્વાસ',
    'login.designed': 'ભારતીય ખેડૂતો માટે ❤️ સાથે ડિઝાઈન કરેલ',
    'login.back': 'મુખ્ય પૃષ્ઠ પર પાછા ફરો',

    'store.badge': 'પ્રીમિયમ કૃષિ ઇનપુટ સ્ટોર',
    'store.title': 'ફસલરક્ષક',
    'store.titleHighlight': 'સ્ટોર',
    'store.subtitle': 'સીધા WhatsApp ઓર્ડરિંગ સાથે ગુણવત્તાયુક્ત જંતુનાશકો, ખાતર અને પાક ઉકેલ',
    'store.pesticides': 'જંતુનાશક',
    'store.fertilizers': 'ખાતર',
    'store.cropProtection': 'પાક સુરક્ષા',
    'store.growthReg': 'વૃદ્ધિ નિયંત્રક',
    'store.catalog': 'એગ્રી સ્ટોર કેટેલોગ',
    'store.catalogDesc': 'WhatsApp ઝડપી ઓર્ડરિંગ સાથે સાચા કૃષિ ઇનપુટ',
    'store.cart': 'કાર્ટ',
    'store.allCategories': 'બધી શ્રેણીઓ',
    'store.searchPlaceholder': 'ઉત્પાદ નામ, પાક, અથવા ઇનપુટ પ્રકાર દ્વારા શોધો',
    'store.maxPrice': 'મહત્તમ ભાવ',
    'store.starAbove': '4 સ્ટાર અને ઉપર',
    'store.location': 'સ્થાન',
    'store.allLocations': 'બધા સ્થાન',
    'store.searchResults': 'શોધ પરિણામો',
    'store.allProducts': 'બધા ઉત્પાદ',
    'store.showing': 'બતાવ્યું',
    'store.of': 'માંથી',
    'store.products': 'ઉત્પાદ',
    'store.loadMore': 'વધુ લોડ કરો',
    'store.noProducts': 'કોઈ ઉત્પાદ મળ્યું નહીં',
    'store.noProductsDesc': 'તમારા ફિલ્ટર અથવા શોધ શબ્દો બદલીને જુઓ.',
    'store.clearFilters': 'બધા ફિલ્ટર સાફ કરો',
    'store.livePrice': 'લાઇવ બજાર ભાવ ઉપલબ્ધ',
    'store.dismiss': 'બંધ કરો',
    'store.addedToCart': 'કાર્ટમાં ઉમેર્યું',
    'store.unsureBuy': '🌿 શું ખરીદવું તે ખ્યાલ નથી?',
    'store.expertDesc': 'AI પાસેથી તાત્કાલિક મદદ મેળવો અથવા નિષ્ણાત સાથે વાત કરો.',
    'store.askAI': 'AI ને પૂછો',
    'store.consultExpert': 'નિષ્ણાત સાથે પરામર્શ',
    'store.recommended': 'તમારી જમીન માટે ભલામણ 🌱',
    'store.packSize': 'પેક સાઇઝ',
    'store.price': 'ભાવ',
    'store.inStock': 'ઉપલબ્ધ',
    'store.outOfStock': 'ઉપલબ્ધ નથી',
    'store.addToCart': 'કાર્ટમાં ઉમેરો',
    'store.added': 'ઉમેર્યું!',
    'store.buyNow': 'હમણાં ખરીદો',
    'store.reviews': 'સમીક્ષા',
    'store.units': 'એકમ',
    'store.yourCart': 'તમારી કાર્ટ',
    'store.itemsSelected': 'આઇટમ પસંદ',
    'store.itemSelected': 'આઇટમ પસંદ',
    'store.subtotal': 'પેટા-કુલ',
    'store.total': 'કુલ',
    'store.clearCart': 'કાર્ટ ખાલી કરો',
    'store.buyAllWhatsapp': 'WhatsApp પર બધું ખરીદો',
    'store.emptyCart': 'તમારી કાર્ટ ખાલી છે',
    'store.emptyCartDesc': 'સ્ટોરમાંથી ઉત્પાદ ઉમેરો અને WhatsApp પર એક જ ઓર્ડર આપો.',
    'store.whyUse': 'આ શા માટે ઉપયોગ કરવો?',
    'store.keyFeatures': 'મુખ્ય વિશેષતાઓ',
    'store.specifications': 'વિશિષ્ટ માહિતી',
    'store.recommended_crops': 'ભલામણ કરેલ પાક',
    'store.usageGuide': 'ઉપયોગ માર્ગદર્શિકા',
    'store.bestFor': 'માટે સૌથી ઉત્તમ',
    'store.season': 'મોસમ',
    'store.addedToCartFull': 'કાર્ટમાં ઉમેર્યું!',
    'store.buyOnWhatsapp': 'WhatsApp પર ખરીદો',
    'store.contactSeller': 'વિક્રેતાનો સંપર્ક કરો',
    'store.paymentNote': 'ચુકવણી અને ડિલિવરી WhatsApp પર સીધા વિક્રેતા સાથે ગોઠવવામાં આવે છે.',
    'store.productOverview': 'ઉત્પાદ અવલોકન',
    'store.composition': 'રચના',
    'store.weight': 'વજન',
    'store.dosage': 'માત્રા',
    'store.application': 'ઉપયોગ પદ્ધતિ',
    'disease.severe': 'ગંભીર',
    'disease.moderate': 'મધ્યમ',
    'disease.mild': 'હળવું',
    'disease.fungal': 'ફૂગ (Fungal)',
    'disease.bacterial': 'બેક્ટેરિયલ (Bacterial)',
    'disease.viral': 'વાયરલ (Viral)',
    'disease.pest': 'જીવાત (Pest)',
    'disease.nutrient': 'પોષક તત્વો (Nutrient)',
    'disease.spreads_fast': 'ઝડપથી ફેલાય છે',
    'disease.gujarat': 'ગુજરાત',
    'disease.aka': 'જેમને ... પણ કહેવાય છે',
    'disease.more_symptoms': 'વધુ લક્ષણો',
    'disease.view_details': 'વિગતો જુઓ',
    'disease.search_placeholder': 'પાક રોગ, લક્ષણો અથવા સ્થાનિક નામો શોધો...',
    'disease.all_crops': 'બધા પાક',
    'disease.clear_filters': 'બધા ફિલ્ટર સાફ કરો',
    'disease.active_filters': 'સક્રિય',
    'disease.symptoms': 'લક્ષણો',
    'disease.causes': 'આ રોગ શા માટે થાય છે?',
    'disease.weather_conditions': 'હવામાનની સ્થિતિ',
    'disease.treatment_plan': 'સારવાર યોજના',
    'disease.organic_alternative': 'જૈવિક / પ્રાકૃતિક વિકલ્પ',
    'disease.how_to_prevent': 'કેવી રીતે અટકાવવું',
    'disease.first_aid_tip': 'પ્રાથમિક સારવાર',
    'disease.affected_states': 'સૌથી વધુ અસરગ્રસ્ત રાજ્યો',
    'disease.quick_actions': 'ત્વરિત પગલાં',
    'disease.scan_my_crop': 'મારા પાકને સ્કેન કરો',
    'disease.share_whatsapp': 'WhatsApp પર શેર કરો',
    'disease.copy_treatment': 'સારવારના પગલાં કોપી કરો',
    'disease.at_a_glance': 'એક નજરમાં',
    'disease.crop': 'પાક',
    'disease.type': 'પ્રકાર',
    'disease.severity': 'ગંભીરતા',
    'disease.spreads': 'ફેલાવો',
    'disease.season': 'મોસમ',
    'disease.yield_loss': 'ઉપજમાં ઘટાડો',
    'disease.contagious': 'ચેપી',
    'disease.similar_diseases': 'સમાન રોગો',
    'disease.other_diseases': 'આ પાકના અન્ય રોગો',
    'disease.no_diseases': 'કોઈ રોગ મળ્યો નહીં',
    'disease.try_different': 'અલગ શબ્દોથી શોધો અથવા ફિલ્ટર સાફ કરો',
    'disease.affected_parts': 'અસરગ્રસ્ત ભાગો',
    'disease.leaf': 'પાંદડું',
    'disease.stem': 'થડ',
    'disease.root': 'મૂળ',
    'disease.fruit': 'ફળ',
    'disease.flower': 'ફૂલ',
    'weather.title': 'કૃષિ-હવામાન કેન્દ્ર',
    'weather.locating': 'ખેતરનું સ્થાન શોધાઈ રહ્યું છે...',
    'weather.search_placeholder': 'ગામ અથવા શહેર શોધો...',
    'weather.detect_location': 'લાઇવ સ્થાન શોધો',
    'weather.syncing': 'હવામાન ઉપગ્રહો સાથે જોડાણ થઈ રહ્યું છે...',
    'weather.current_temp': 'વર્તમાન તાપમાન',
    'weather.soil_humidity': 'જમીનનો ભેજ',
    'weather.wind_speed': 'પવનની ગતિ',
    'weather.rain_prob': 'વરસાદની શક્યતા',
    'weather.air_soil_sat': 'હવા-જમીન સંતૃપ્તિ',
    'weather.avg_wind': 'સરેરાશ વર્તમાન ગતિ',
    'weather.precip_risk': 'વરસાદનું જોખમ',
    'weather.radar_title': 'ઇન્ટરેક્ટિવ કૃષિ રડાર',
    'weather.windy_title': 'વિન્ડી ગ્લોબલ વિઝ્યુલાઇઝેશન',
    'weather.satellite_mode': 'સેટેલાઇટ (ઇન્ટરેક્ટિવ)',
    'weather.windy_mode': 'વિન્ડી (વિઝ્યુઅલ્સ)',
    'weather.wind_animation_note': 'પવન એનિમેશન મોડ (માત્ર જોવા માટે)',
    'weather.ai_advice_title': 'AI ઇન્ટેલિજન્સ સલાહ',
    'weather.irrigation_log': 'પિયત લોગ',
    'weather.climate_trends': 'હવામાન વલણો (7-દિવસ)',
    'weather.temp_unit': 'તાપમાન (°C)',
    'weather.rain_unit': 'વરસાદની શક્યતા (%)',
    'weather.clear': 'ચોખ્ખું આકાશ',
    'weather.sunny': 'તડકો',
    'weather.p_cloudy': 'થોડા વાદળો',
    'weather.cloudy': 'વાદળછાયું',
    'weather.foggy': 'ધુમ્મસવાળું',
    'weather.rainy': 'વરસાદી',
    'weather.showers': 'ઝાપટા',
    'weather.storm': 'વાવાઝોડું',
    'weather.advice_humidity': 'વધારે ભેજ. પાનમાં ગેરુ રોગનું જોખમ.',
    'weather.advice_rain': 'વધારે વરસાદની શક્યતા. ઘન ખાતર નાખશો નહીં.',
    'weather.advice_heat': 'ભીષણ ગરમીની ચેતવણી. તરત જ બમણું પિયત આપો.',
    'weather.advice_wind': 'તેજ પવન. ઊંચા છોડને ટેકો આપો.',
    'weather.advice_optimal': 'આજે ખેતી માટે અનુકૂળ પરિસ્થિતિ છે.',
    'weather.irrigation_heavy_rain': '⚠️ ભારે વરસાદની શક્યતા. જમીનનું ધોવાણ રોકવા માટે આગામી 24 કલાક પિયત બંધ રાખો.',
    'weather.irrigation_clear': '✅ ચોખ્ખું આકાશ. સવારે 6:00 થી 9:00 વચ્ચે સામાન્ય પિયત આપો.',
    'weather.location_verified': 'સ્થાન ચકાસણી સફળ',
    'weather.current_selection': 'વર્તમાન પસંદગી',
    'weather.fetch_failed': 'આ સ્થાન માટે હવામાનની માહિતી મળી નથી.'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('fasalrakshak_lang') || 'HI');

  useEffect(() => {
    localStorage.setItem('fasalrakshak_lang', lang);
  }, [lang]);

  const t = (key) => {
    let result = translations[lang];
    
    // Check for flat keys first (as defined in our dictionary)
    if (result && result[key] !== undefined) {
      return result[key];
    }

    // Fallback for nested keys (just in case)
    const keys = key.split('.');
    let current = result;
    for (const k of keys) {
      if (current && current[k] !== undefined) {
        current = current[k];
      } else {
        // Return key name if not found to help debugging
        // But for arrays, we should return an empty array to prevent .map() crashes
        if (key.includes('Links') || key.includes('items') || key.includes('steps')) {
          return [];
        }
        return key; 
      }
    }
    return current;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
